-- Lab 4 -- 
-- 1)
SELECT ORDERS.order_num, CUSTOMERS.firstname, CUSTOMERS.lastname, ORDERS.orderdate
FROM ORDERS NATURAL JOIN CUSTOMERS
WHERE shipdate is null
ORDER BY orderdate asc;

-- 2)
SELECT CUSTOMERS.customer_num, CUSTOMERS.firstname, CUSTOMERS.lastname, ORDERITEMS.order_num
FROM CUSTOMERS NATURAL JOIN ORDERS 
NATURAL JOIN ORDERITEMS
NATURAL JOIN BOOKS
WHERE BOOKS.Category = 'COMPUTER' and CUSTOMERS.State = 'FL';

-- 3)
SELECT DISTINCT BOOKS.title
FROM CUSTOMERS JOIN ORDERS
ON CUSTOMERS.Customer_num = ORDERS.Customer_num JOIN ORDERITEMS
ON ORDERS.Order_num = ORDERITEMS.Order_num JOIN BOOKS
ON BOOKS.ISBN = ORDERITEMS.ISBN
WHERE CUSTOMERS.FirstName = 'JAKE' and CUSTOMERS.LastName = 'LUCAS';

-- 4)
SELECT BOOKS.title, ORDERS.orderdate, (ORDERITEMS.PaidEach - BOOKS.Cost) AS profit
FROM CUSTOMERS JOIN ORDERS
ON CUSTOMERS.Customer_num = ORDERS.Customer_num JOIN ORDERITEMS
ON ORDERS.Order_num = ORDERITEMS.Order_num JOIN BOOKS
ON BOOKS.ISBN = ORDERITEMS.ISBN
WHERE CUSTOMERS.FirstName = 'JAKE' and CUSTOMERS.LastName = 'LUCAS'
ORDER BY ORDERS.orderdate asc, profit desc;

-- 5)
SELECT BOOKS.ISBN, BOOKS.Title
FROM AUTHOR JOIN BOOKAUTHOR
ON AUTHOR.AuthorID = BOOKAUTHOR.AuthorID JOIN BOOKS
ON BOOKAUTHOR.ISBN = BOOKS.ISBN
WHERE AUTHOR.Lname = 'ADAMS';

-- 6)
SELECT AUTHOR.fname, AUTHOR.lname, BOOKS.title
FROM CUSTOMERS JOIN ORDERS
USING(customer_num) JOIN ORDERITEMS
USING(order_num) JOIN BOOKS
USING(isbn) JOIN BOOKAUTHOR
USING(isbn) JOIN AUTHOR
USING(authorid)
WHERE CUSTOMERS.FirstName = 'BECCA' and CUSTOMERS.LastName = 'NELSON';

-- 7)
SELECT BOOKS.Title, ORDERS.Order_num, CUSTOMERS.State
FROM BOOKS LEFT JOIN ORDERITEMS
ON BOOKS.ISBN = ORDERITEMS.ISBN LEFT JOIN ORDERS
ON ORDERITEMS.Order_num = ORDERS.Order_num LEFT JOIN CUSTOMERS
ON ORDERS.Customer_num = CUSTOMERS.Customer_num;

-- 8)
SELECT COUNT(*)
FROM BOOKS
WHERE BOOKS.Retail >= 30;

-- 9)
SELECT MAX(pubdate)
FROM BOOKS;

-- 10)
SELECT SUM((BOOKS.Retail - BOOKS.Cost)*ORDERITEMS.Quantity) AS 'Total Profit'
FROM CUSTOMERS JOIN ORDERS
USING(customer_num) JOIN ORDERITEMS
USING(order_num) JOIN BOOKS
USING(isbn)
WHERE CUSTOMERS.Customer_num = 1017;

-- 11)
SELECT MIN(retail)
FROM BOOKS;

-- 12)
SELECT customer_num, COUNT(*)
FROM ORDERS
GROUP BY customer_num;

-- 13)
SELECT PUBLISHER.Name, BOOKS.Category, AVG(Retail)
FROM BOOKS JOIN PUBLISHER
USING(PubID)
WHERE BOOKS.Category IN(PUBLISHER.Name, BOOKS.Category)
AND (BOOKS.Retail > 50)
GROUP BY PUBLISHER.Name, BOOKS.Category;

-- 14)
SELECT CUSTOMERS.FirstName, CUSTOMERS.LastName, ORDERS.Order_num, SUM(retail * quantity) AS Total
FROM CUSTOMERS JOIN ORDERS
USING(customer_num) JOIN ORDERITEMS
USING(order_num) JOIN BOOKS
USING(isbn)
WHERE CUSTOMERS.State = 'FL' OR CUSTOMERS.State = 'GA'
GROUP BY order_num desc
HAVING SUM(retail * quantity) > 80;

-- 15)
SELECT MAX(retail)
FROM BOOKS JOIN BOOKAUTHOR
USING(isbn) JOIN AUTHOR
USING(AuthorID)
WHERE AUTHOR.Fname = 'LISA' 
AND AUTHOR.Lname = 'WHITE';
